apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-manager-cluster
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-manager-cluster-binding
subjects:
  - kind: ServiceAccount
    name: resource-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: resource-manager-cluster
  apiGroup: rbac.authorization.k8s.io